name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: '9.15.0'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-0 libnotify4 libnss3 libxss1 libxtst6 xdg-utils libatspi2.0-0 libuuid1 libsecret-1-0 libappindicator3-1

      - name: Get package version
        id: package-version
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          echo "version=$PACKAGE_VERSION" >> $GITHUB_OUTPUT

      - name: Get short commit hash
        id: commit-hash
        run: |
          SHORT_HASH=$(git rev-parse --short HEAD)
          echo "hash=$SHORT_HASH" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build application
        run: pnpm run build

      - name: Build Linux distribution
        run: pnpm run dist:linux

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.package-version.outputs.version }}-gxjakkap.${{ steps.commit-hash.outputs.hash }}
          name: Release ${{ steps.package-version.outputs.version }}-gxjakkap.${{ steps.commit-hash.outputs.hash }}
          draft: false
          prerelease: false
          files: |
            dist/*.deb
            dist/*.rpm
            dist/*.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: '9.15.0'

      - name: Get package version
        id: package-version
        run: |
          $version = (Get-Content package.json | ConvertFrom-Json).version
          echo "version=$version" >> $env:GITHUB_OUTPUT

      - name: Get short commit hash
        id: commit-hash
        run: |
          $hash = git rev-parse --short HEAD
          echo "hash=$hash" >> $env:GITHUB_OUTPUT

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build application
        run: pnpm run build

      - name: Build Windows distribution
        run: pnpm run dist:win

      - name: Upload Windows artifacts to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.package-version.outputs.version }}-gxjakkap.${{ steps.commit-hash.outputs.hash }}
          name: Release ${{ steps.package-version.outputs.version }}-gxjakkap.${{ steps.commit-hash.outputs.hash }}
          draft: false
          prerelease: false
          files: |
            dist/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
